name: "CHANNEL ASSETS"

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php modules/channels_assets.php
          git config --global user.email "rezagah.milad@gmail.com"
          git config --global user.name "miladesign"
          git config credential.helper store
          git add -A
          git commit -m "🚀 Channels Update - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
